### DISCUSSION TITLE
TOML: alternative for generative env and factor?

### DISCUSSION THREAD

**Discussion by abelcheung** [tox-dev/tox#3432] [General]
Facing some hurdle here when migrating ini to toml. Without generative env and factor support, I found myself creating lots of repetitive and almost identical envs, differed by only 1 or 2 keys. For example:

```toml
[env._basic]
change_dir = '{toxroot}/dir'
commands_pre = [['some', 'command']]
commands = [['other', 'looooong', 'command']]

[env.env1]
dependency_groups = ['a', 'b']
change_dir   = {replace = 'ref', of = ['env', '_basic', 'change_dir'  ]}
commands_pre = {replace = 'ref', of = ['env', '_basic', 'commands_pre']}
commands     = {replace = 'ref', of = ['env', '_basic', 'commands'    ]}

[env.env2]
dependency_groups = ['a', 'c']
change_dir   = {replace = 'ref', of = ['env', '_basic', 'change_dir'  ]}
commands_pre = {replace = 'ref', of = ['env', '_basic', 'commands_pre']}
commands     = {replace = 'ref', of = ['env', '_basic', 'commands'    ]}

[env.env3]
dependency_groups = ['a', 'd']
change_dir   = {replace = 'ref', of = ['env', '_basic', 'change_dir'  ]}
commands_pre = {replace = 'ref', of = ['env', '_basic', 'commands_pre']}
commands     = {replace = 'ref', of = ['env', '_basic', 'commands'    ]}

# ..... (and so on) .....
```

Currently `[env_run_base]` is not a good option as I have 2 large groups of envs, one following a set of defaults and another following another set of defaults. Is there any other option to simplify the mess?

**Comment by gaborbernat** [comment]
You can change the base environment key via https://tox.wiki/en/latest/config.html#base.

**Reply by abelcheung** [reply]
Thanks, it worked wonders! Envs become much more manageable by combining various bases now. Wish I notice this setting earlier.

**Comment by gaborbernat** [comment]
To expand on the `base` suggestion — for your case with two groups of envs following different defaults, you can define two base environments and point each group to the appropriate one:

```toml
[env._group_a]
change_dir = "{toxroot}/dir"
commands_pre = [["some", "command"]]
commands = [["other", "looooong", "command"]]

[env._group_b]
change_dir = "{toxroot}/other_dir"
commands_pre = [["different", "command"]]
commands = [["another", "command"]]

[env.env1]
base = ["_group_a"]
dependency_groups = ["a", "b"]

[env.env2]
base = ["_group_a"]
dependency_groups = ["a", "c"]

[env.env3]
base = ["_group_b"]
dependency_groups = ["x", "y"]
```

Each env only needs to declare `base` and the keys that differ. Everything else is inherited from the base env.
