### ISSUE TITLE
[BUG] Tox fails to install package with requirements in pyproject.toml

### ISSUE THREAD

**Issue by unmade** [tox-dev/tox#1236]
I've been using tox (3.7.0) with flit as a build backend. After upgrading to tox 3.8 I keep getting this error whenever try to run tox:

```AttributeError: 'VirtualEnv' object has no attribute 'newaction'```

My tox.ini
```ini
[tox]
isolated_build = True
envlist =
    test

[tox:.package]
basepython = python3

[testenv]
skip_install = False
deps = 
    pytest
commands = 
    test: pytest -s
```

My pyproject.toml
```toml
[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "***"
dist-name = "***"
author = "***"
author-email = "***"
requires-python=">=3.7,<4"
description-file="README.md"
requires = [
    "typing-extensions >= 3.7.2,<4",
    "jwcrypto >= 0.6.0,<1",
]
```

I prepared pull request that fixes this bug: https://github.com/tox-dev/tox/pull/1235
