### ISSUE TITLE
Color support on Windows: TerminalWriter (PY_COLORS), colorama (PYCHARM_HOSTED)

### ISSUE THREAD

**Issue by eine** [tox-dev/tox#1468]
While running several tests with `tox` on GitHub Actions environments, tox's output is not coloured by default (see actions/starter-workflows#114). Setting `PY_COLORS: 1` (#1009) works for jobs running on GNU/Linux (`ubuntu-latest`). Unfortunately, it seems not to be effective on `windows-latest`.

- `ubuntu-latest`: https://github.com/1138-4EB/vunit/runs/326860648#step:5:29
- `windows-latest`: https://github.com/1138-4EB/vunit/runs/326860617#step:7:31

Note that, in those examples, the output of the commands executed by tox is coloured because `--color=yes` is explicitly passed to `pytest` through `{posargs}`.

**Comment by gaborbernat** [comment]
We'd happy to fix this if someone can investigate and come up with a PR for it.

**Comment by 1138-4EB** [comment]
I'd be happy to investigate if I have any reference. Currently, `PY_COLORS` seems not to be found in this repository, except in the help: https://github.com/tox-dev/tox/search?q=PY_COLORS&type=Code

**Comment by 1138-4EB** [comment]
Here is a minimal reproducer GitHub Actions workflow:

```yml
name: "tox"
on: [push]
jobs:
  tox:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ ubuntu, windows ]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/checkout@v1
    - run: pip3 install tox --progress-bar off
    - run: tox -e py37-test
    - run: tox -e py37-test
      env:
        PY_COLORS: 1
```

Output: https://github.com/1138-4EB/actions/runs/327196070
