### ISSUE TITLE
Cant run bash from GitHub CI

### ISSUE THREAD

**Issue by madhavajay** [tox-dev/tox#2416]
I have this really weird issue where if I run tox from github CI it wont let me use `bash` inside tox. If I run this locally myself in windows or by hand on the CI machine everything is fine.

So here is an example where I run something in bash which then uses || true if it fails.

I also tried escaping with `^|^|` but that didnt work.
```
commands =
    bash -c "docker volume rm test_domain_1_app-db-data --force || true"
```

<img width="727" alt="Screen Shot 2022-05-10 at 4 57 16 pm" src="https://user-images.githubusercontent.com/2882739/167567470-e3167ba3-3686-40e6-b424-363c738671a3.png">

To run the tox tasks I do:
```
- name: Run integration tests
        if: steps.changes.outputs.stack == 'true'
        timeout-minutes: 30
        env:
          HAGRID_ART: false
        run: |
          tox -e stack.test.integration.windows
        shell: cmd
```

It says its shell: cmd, but I have also tried running `powershell.exe -command "tox -e stack.test.integration.windows" to no avail.

I can't figure it out. Its like the quotes are changing to single quotes somehow and then its failing, but why? Is there some way to control what shell gets used for each line under `command` when running in windows?

Why does this only happen with the github ci runner and not when I run the command by hand?
