### ISSUE TITLE
`tox` + `poetry`: unable to find installation candidates for existing package `lalsuite==7.6`

### ISSUE THREAD

**Issue by jacopok** [tox-dev/tox#2483]
Hello, I am posting this issue here as opposed to the `poetry` issue tracker since the problem only seems to occur when using tox in conjunction with poetry, but if further investigation were to show that tox is not at the root of the problem I'd be happy to move it. 

I have a minimal example of a poetry-managed project with the following `pyproject.toml`:
```toml
[tool.poetry]
name = "example_project"
version = "0.0.1"
description = "Demonstrating an issue."
license = "GNU GPL3"
authors = ["Jacopo Tissino <jacopo@tissino.it>"]


[tool.poetry.dependencies]
python = ">=3.7,<3.8"
lalsuite = "7.6"

[tool.poetry.dev-dependencies]
tox = "3.25.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

It's using version 7.6 of the gravitational wave analysis package [lalsuite](https://pypi.org/project/lalsuite/), which is the latest as one may check from pypi.

Now, running `poetry update` will show that this `toml` file works correctly, and all the required packages are installed: 

```bash
$ poetry update
Using python3 (3.7.12)
Creating virtualenv example-project-XgA7aOpM-py3.7 in /home/jacopo/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (0.4s)

Package operations: 29 installs, 0 updates, 0 removals

  • Installing pyparsing (3.0.9)
  • Installing cryptography (37.0.4)
  • Installing numpy (1.21.6)
  • Installing packaging (21.3)
  • Installing six (1.16.0)
  • Installing tomli (2.0.1)
  • Installing cycler (0.11.0)
  • Installing distlib (0.3.5)
  • Installing filelock (3.8.0)
  • Installing fonttools (4.36.0)
  • Installing kiwisolver (1.4.4)
  • Installing ligo-segments (1.4.0)
  • Installing pillow (9.2.0)
  • Installing platformdirs (2.5.2)
  • Installing pyerfa (2.0.0.1)
  • Installing pyopenssl (22.0.0)
  • Installing pyrxp (3.0.1)
  • Installing python-dateutil (2.8.2)
  • Installing setuptools-scm (6.4.2)
  • Installing astropy (4.3.1)
  • Installing lscsoft-glue (3.0.1)
  • Installing matplotlib (3.5.3)
  • Installing pluggy (1.0.0)
  • Installing py (1.11.0)
  • Installing scipy (1.7.3)
  • Installing toml (0.10.2)
  • Installing virtualenv (20.16.3)
  • Installing lalsuite (7.6)
  • Installing tox (3.25.1)
```

Notice that lalsuite version 7.6 is installed without issues.

Now, I create the following `tox.ini`:

```ini
[tox]
skipsdist = true
envlist = py{37}
isolated_build = true

[testenv]
allowlist_externals = 
    poetry
    echo
require_locked_deps = true
install_dev_deps = true
list_dependencies_command = echo
commands =
    poetry run python --version
    poetry install -vvv
```

(in the real case this is taken from, those commands are followed by running black, pytest and so on)

With this, I can run `poetry run tox -rvv -e py37`, which fails, with the relevant part of the output being:
```
  • Installing lalsuite (7.6): Failed

  RuntimeError

  Unable to find installation candidates for lalsuite (7.6)

  at ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/chooser.py:72 in choose_for
       68│ 
       69│             links.append(link)
       70│ 
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│ 
       76│         # Get the best link
```

The full verbose output is attached here: [output.txt](https://github.com/tox-dev/tox/files/9401614/output.txt), but nothing really informative seems to be there.

I'm at a loss: the package clearly exists, poetry is able to find it, but it cannot do so when working inside tox?!
Thanks in advance for any help!
