### ISSUE TITLE
RFE: Prefer TOML-native configuration over legaci INI

### ISSUE THREAD

**Issue by hroncok** [tox-dev/tox#3402]
## What's the problem this feature will solve?

 - I want old tox versions to know I need tox \>= 4.21
 - I want to use TOML-native configuration

If I have this:

```toml
[tool.tox]
requires = ["tox>=4.21"]
env_list = ["3.13", "3.12", "type", "doc"]
...
```

The old tox does not read it and ignores it.

If I change it like this:

```toml
[tool.tox]
legacy_tox_ini = """
    [tox]
    min_version = 4.21
"""
env_list = ["3.13", "3.12", "type", "doc"]
...
```

The old tox reads it and updates tox in the provision venv.
However, the TOML-native configuration is ignored by the new tox.

## Describe the solution you'd like

I believe this could be solved if the new tox preferred the TOML-native configuration over legacy_tox_ini if both exist.

## Alternative Solutions

I could stick with legacy_tox_ini unless I know all environments are fully updated to tox > 4.21.

Thanks
