### ISSUE TITLE
Tox supports PyPy?

### ISSUE THREAD

**Issue by Ada-lave** [tox-dev/tox#3494]
When i trying add pypy to env_list like a
```toml
env_list = ["cpython310", "pypy310"]

[env."cpython310"]
deps = [
    "-r requirements-cython.txt",
    "-r requirements.dev.txt"
]
description = "Start bench"
commands = [["pytest","tests", "--benchmark-autosave"]]
```

i got waring like that:
pypy: skipped because could not find python interpreter with spec(s): pypy
